services:
  bot:
    build: bot
    deploy:
      replicas: 1
    environment:
      REGISTRY_HOST: registry
      REGISTRY_PORT: 8080
      LISTEN_PORT: 8080
      MCSERVER_HOST: mcserver
      MCSERVER_PORT: 25565
      MCSERVER_VERSION: 1.20.1
    restart: always

  mcserver:
    environment:
      EULA: TRUE
      MAX_PLAYERS: 100
      ONLINE_MODE: FALSE
      SERVER_PORT: 25565
      VERSION: 1.20.1
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    restart: always
    volumes:
      - mcserver:/data

  registry:
    build: registry
    environment:
      LISTEN_PORT: 8080
    restart: always

volumes:
  mcserver:
