[tool.poetry]
name = "dragon-hunters-policymaker"
version = "0.0.0"
description = ""
authors = ["Futrime <futrime@outlook.com>"]
packages = [{include = "policymaker"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
